cms/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # /cms/,
    url(r'^login/$', views.cmsLogin, name='login'),
    url(r'^register/$', views.cmsRegister, name='register'),
    url(r'^certification_upload/$', views.cmsCertificationUpload, name='certification-upload'),
    url(r'^dashboard/$', views.cmsDashBoard, name='dashboard'),
    url(r'^company_create/$', views.cmsCompanyCreate, name='company-create'),
    url(r'^position_create/$', views.cmsPositionCreate, name='position-create'),
    url(r'^position_list/$', views.cmsPositionList, name='position-list'),
    url(r'^position_update/(?P<uuid>.+)/$', views.PositionUpdateView.as_view(), name='position-update'),
    url(r'^position_delete/(?P<uuid>.+)/$', views.PositionDeleteView.as_view(), name='position-delete'),
    url(r'^application_reject/(?P<id>.+)/$', views.cmsRejectApplication, name='application-reject'),
    url(r'^received_applications/$', views.cmsReceivedApplications, name='application-received-list'),
    url(r'^show_application/(?P<id>.+)/$', views.cmsShowApplication, name='application-show'),
    url(r'^invitation_create/$', views.cmsInvitationCreate, name='invitation-delete'),
    url(r'^sent_invitations/$', views.cmsSentInvitations, name='invitation-sent-list'),
    url(r'^show_invitation/(?P<id>.+)/$', views.cmsShowInvitation, name='invitation-show'),
    ]

cms/models.py
from django.db import models

# Create your models here.
# Use profiles models and accounts models

profiles/models.py
# -*- coding: UTF-8 -*-
import os, uuid
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from .utils import user_directory_path, resume_directory_path, validate_hr_doc_extension,validate_resume_extension, get_default_image
from accounts.utils import create_proflie, create_hrproflie

from django.core.signals import request_finished

# Create your models here.
User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    EDU_BACHELOR = 1
    EDU_MASTER = 2
    EDU_PHD = 3
    EDU_MBA = 4
    EDU_OTHER = 5
    EDUCATION_DEGREE = [(EDU_BACHELOR, u'本科'),
                        (EDU_MASTER, u'硕士'),
                        (EDU_PHD, u'博士'),
                        (EDU_MBA, 'MBA'),
                        (EDU_OTHER, u'其他')]
    SERVICE_STUDENT, SERVICE_GRADUATE, SERVICE_YEAR1, SERVICE_YEAR2, SERVICE_YEAR3, SERVICE_YEAR4, SERVICE_YEAR5, \
    SERVICE_YEAR10, SERVICE_10MORE = list(range(1, 10))

    SERVICE_YEARS = [(SERVICE_STUDENT, u'在读'),
                     (SERVICE_GRADUATE, u'应届生'),
                     (SERVICE_YEAR1, u'1-3年'),
                     (SERVICE_YEAR2, u'3-5年'),
                     (SERVICE_YEAR3, u'5年以上'),]

    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    first_name = models.CharField(_(u'名'), max_length=30,  null=True)
    last_name = models.CharField(_(u'姓'), max_length=30,  null=True)
    edu_degree = models.IntegerField(_(u'学历'), choices=EDUCATION_DEGREE, null=True)
    service_years = models.IntegerField(_(u'工作年限'), choices=SERVICE_YEARS, null=True)
    # tel = PhoneNumberField(_(u'手机号码'), max_length=15, null=True)
    tel = models.CharField(_(u'手机号码'), max_length=15, null=True)
    email = models.EmailField(_(u'个人邮箱'), null=True)
    address = models.CharField(_(u'现居地'), max_length=10, null=True)
    description = models.TextField(_(u'个人简介'), null=True)
    avatar = models.ImageField(_(u'照片'), upload_to=user_directory_path,blank=True,null=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True,)
    class Meta:
        db_table = 'profiles'
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        if self.last_name == None:
            return None
        else:
            full_name = '{0}{1}'.format(self.last_name, self.first_name)
            return full_name.strip()

    def query_work_exp(self,):
        return WorkExperience.objects.filter(user=self.user)

    def query_edu_exp(self,):
        return EducationalExperience.objects.filter(user=self.user)

    def query_skills(self,):
        return Skill.objects.filter(user=self.user)


class HRProfile(models.Model):
    STATUS_NOT_CERTIFICATED = 1
    STATUS_IN_PROGRESS = 2
    STATUS_CERTIFICATED = 3
    STATUS = [(STATUS_NOT_CERTIFICATED, u"未认证"), (STATUS_IN_PROGRESS, u"认证中"), (STATUS_CERTIFICATED, u"已认证"),
              ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    name = models.CharField(_(u'名'), max_length=30,  null=True)
    company = models.CharField(_(u'所在公司'), max_length=50,  null=True)
    position = models.CharField(_(u'现任职位'), max_length=30,  null=True)
    is_certificated = models.BooleanField(_(u'已认证'), default=False)
    status = models.IntegerField(_(u'认证状态'), choices=STATUS, default=STATUS_NOT_CERTIFICATED)
    certificated_doc = models.FileField(upload_to=resume_directory_path, validators=[validate_hr_doc_extension], null=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, )
    class Meta:
        db_table = 'profiles_hr'
        verbose_name = _('profile for hr')
        verbose_name_plural = _('profiles for hrs')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return self.name



class WorkExperience(models.Model):
    company = models.CharField( max_length=200, blank=False)
    position = models.CharField( max_length=100, blank=False)
    start_date = models.CharField( max_length=10, blank=False)
    end_date = models.CharField( max_length=10, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, )

    class Meta:
        db_table = 'profiles_work_exp'
        verbose_name = _('Work Experience')
        verbose_name_plural = _('Work Experience')


class EducationalExperience(models.Model):
    EDU_BACHELOR = 1
    EDU_MASTER = 2
    EDU_PHD = 3
    EDU_MBA = 4
    EDUCATION_DEGREE = [(EDU_BACHELOR, u'本科'),
                        (EDU_MASTER, u'硕士'),
                        (EDU_PHD, u'博士'),
                        (EDU_MBA, 'MBA')]
    college = models.CharField(_(u'学校'), max_length=200, blank=False)
    major = models.CharField(_(u'专业'), max_length=100, blank=False)
    degree = models.IntegerField(_(u'学历'), choices=EDUCATION_DEGREE, blank=False)
    graduate_date = models.DateField(_(u'毕业年份'),blank=False,)
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, )

    class Meta:
        db_table = 'profiles_edu_exp'
        verbose_name = _('Educational Experience')
        verbose_name_plural = _('Educational Experience')

class Skill(models.Model):
    LEVEL_1 = 1
    LEVEL_2 = 2
    LEVEL_3 = 3
    LEVEL_4 = 4
    LEVEL_5 = 5
    SKILL_LEVEL = [ (LEVEL_1, u'入门'),
                    (LEVEL_2, u'掌握'),
                    (LEVEL_3, u'熟练'),
                    (LEVEL_4, u'精通'),
                    (LEVEL_5, u'专家'), ]

    name = models.CharField(_(u'技能'), max_length=50, blank=False)
    level = models.IntegerField(_(u'水平'), choices=SKILL_LEVEL, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, )

    class Meta:
        db_table = 'profiles_skills'
        verbose_name = _('Educational Experience')
        verbose_name_plural = _('Educational Experience')


class Resume(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    resume = models.FileField(upload_to=resume_directory_path, validators=[validate_resume_extension])

    class Meta:
        db_table = 'profiles_resume'
        verbose_name = _('Personal Resume')
        verbose_name_plural = _('Personal Resumes')


@receiver(models.signals.post_delete, sender=Profile)
def auto_delete_avatar_on_delete(sender, instance, **kwargs):
    import shutil
    """
    Deletes file from filesystem
    when corresponding `Profile` object is deleted.
    """
    if instance.avatar:
        if os.path.isdir(os.path.dirname(instance.avatar.path)):
            shutil.rmtree(os.path.dirname(instance.avatar.path))


@receiver(models.signals.post_delete, sender=Resume)
def auto_delete_resume_on_delete(sender, instance, **kwargs):
    import shutil
    """
    Deletes file from filesystem
    when corresponding `Profile` object is deleted.
    """
    if instance.resume:
        if os.path.isdir(os.path.dirname(instance.resume.path)):
            shutil.rmtree(os.path.dirname(instance.resume.path))

@receiver(models.signals.post_delete, sender=Resume)
def auto_delete_resume_on_put(sender, instance, **kwargs):
    import shutil
    """
    Deletes file from filesystem
    when corresponding `Profile` object is deleted.
    """
    if instance.resume:
        if os.path.isdir(os.path.dirname(instance.resume.path)):
            shutil.rmtree(os.path.dirname(instance.resume.path))

@receiver(create_proflie)
def auto_create_profile_on_user_create(sender, instance, **kwargs):
    if instance.id:
        obj = Profile(user=instance, avatar=get_default_image())
        obj.save()

@receiver(create_hrproflie)
def auto_create_hrprofile_on_user_create(sender, instance, **kwargs):
    name = kwargs['name']
    company = kwargs['company']
    position = kwargs['position']

    if instance.id:
        obj = HRProfile(user=instance, company=company, position=position, name=name, )
        obj.save()

cms/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from django.db.models import Q
from django.contrib.auth.hashers import make_password
from captcha.fields import CaptchaField
from hire.models import Company, Position
from functions.models import Invitation

User = get_user_model()

class RegisterForm(UserCreationForm):
    username = forms.CharField(label=u"用户名", max_length=150, )
    name = forms.CharField(label=u"姓名", max_length=10, help_text=_(u'请输入工作中使用的姓名'))
    password1 = forms.CharField(
        label=_(u'密码'),
        strip=False,
        widget=forms.PasswordInput,
        # help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_(u"确认密码"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_(u"再次输入密码"),
    )
    # password = forms.CharField(widget=forms.PasswordInput(),label=u'密码', required=True,)
    # comfirmed_password = forms.CharField(widget=forms.PasswordInput(), label=u"确认密码",required=True,)
    email = forms.EmailField(label=u"邮箱",required=True, help_text=_(u'请输入工作邮箱'))
    company = forms.CharField(label=u"公司", max_length=30, required=True, help_text=_(u'请填写与营业执照/劳动合同一致的公司名称'))
    position = forms.CharField(label=u"职位", max_length=20, required=True, help_text=_(u'请输入当前职位'))
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ("username","email",)

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.password = make_password(self.cleaned_data["password1"])
        user.is_staff = True
        if commit:
            user.save()
        return user

class LoginForm(AuthenticationForm):
    username = UsernameField(
        label=_(u"用户名或邮箱"),
        required=True,
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True}),
        error_messages={
            'required': _(u"请输入用户名或邮箱！"),
        }
    )
    password = forms.CharField(
        label=_(u"密码"),
        strip=False,
        required=True,
        widget=forms.PasswordInput,
        error_messages={
            'required': _(u"请输入密码！"),
        }
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
        'user_not_existed': _(u"用户不存在！"),
        'password_wrong': _(u"密码不正确！")
    }

    def is_valid(self):
        return self.is_bound and not self.errors

    def confirm_login_allowed(self, user):
        print(user)
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',)

class CertificationUploadForm(forms.Form):
    file = forms.FileField(required=True, error_messages={'required': _(u"请选择文件！")})

class CompanyCreateForm(ModelForm):
    industry = forms.ChoiceField(choices=Company.INDUSTRY, initial=Company.INDUSTRY_BANK)
    size = forms.ChoiceField(choices=Company.SIZE, initial=Company.SIZE_SMALL)
    stock = forms.ChoiceField(choices=Company.STOCK, initial=Company.STOCK_NONE)
    name = forms.CharField(required=True,max_length=100, error_messages={'required': _(u"请输入公司名称！")})
    introduction = forms.CharField(widget=forms.Textarea(attrs={'class': "textarea"}),)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': "textarea"}), )
    class Meta:
        model = Company
        fields = (
            'name',
            'web_site',
            'industry',
            'size',
            'stock',
            'introduction',
            'description',
            'photo',
            'shareholders',
            'abbreviation',
            'headquarters',
        )

class PositionCreateForm(ModelForm):
    name = forms.CharField(required=True,max_length=100, error_messages={'required': _(u"请输入职位名称！")})
    salary = forms.ChoiceField(choices=Position.SALARY_LEVEL,initial=Position.SALARY_LEVEL1)
    category = forms.ChoiceField(choices=Position.CATEGORY,initial=Position.CATEGORY_FUNCTION)
    type = forms.ChoiceField(choices=Position.TYPE, initial=Position.TYPE_GRADUATION)
    work_exp_req = forms.ChoiceField(choices=Position.WORK_EXP_REQ, initial=Position.WORK_EXP_LEVEL1)
    edu_req = forms.ChoiceField(choices=Position.EDUCATION_DEGREE, initial=Position.EDU_BACHELOR)
    duty = forms.CharField(widget=forms.Textarea(attrs={'class': "textarea form-control"}),)
    detail_req = forms.CharField(widget=forms.Textarea(attrs={'class': "textarea form-control"}), )

    class Meta:
        model=Position
        fields = (
            'name',
            'company',
            'department',
            'salary',
            'category',
            'type',
            'work_exp_req',
            'edu_req',
            'email',
            'duty',
            'detail_req',
            'city',
            'address',
        )

class InvitationCreateForm(ModelForm):
    user_uuid = forms.UUIDField(widget = forms.HiddenInput(),required=True)
    position_uuid = forms.UUIDField(widget = forms.HiddenInput(), required=True)
    application = forms.IntegerField(widget = forms.HiddenInput(), required=True)
    interview_time = forms.DateTimeField(required=True)
    class Meta:
        model= Invitation
        fields = (
            'interview_time',
            'interview_address',
            'content',
        )

cms/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}DashBoard{% endblock %}

{% block content %}

  <h2>职位管理</h2>
    {% if my_positions %}
        <ul>
            {% for position in my_positions %}
                <li>
                    <ul>
                        <li>职位： {{ position.name }}</li>
                        <li>公司： {{ position.company }}</li>
                        <li>
                            <a href="/cms/position_update/{{ position.uuid }}/" class="btn btn-outline-info btn-sm" role="button" value="修改">修改</a>
{#                            <button class="btn btn-outline-primary btn-sm" type="button" value="修改" >修改</button>#}
                            <button class="btn btn-outline-danger btn-sm" type="button" value="删除" onclick="delete_position('/cms/position_delete/{{ position.uuid }}/')">删除</button>
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% load cms_my_filter %}
    <h2>投递管理</h2>
    {% if received_applications %}
        {% if invitation_form %}
            {% include 'modal_base_createInvitation.html' with modal_form_id="new-invitation" modal_form_title="Create a New Invitation" modal_form_method="POST" modal_form_action="/cms/invitation_create/" form=invitation_form %}
        {% endif %}
        <ul>
            {% for application in received_applications %}
                <li>
                    <ul>
                        <li>申请人： {{ application.user.profile.last_name}} {{application.user.profile.first_name }}</li>
                        <li>申请人学历： {{ application.user.profile.get_edu_degree_display}}</li>
                        <li>申请人工作经验： {{ application.user.profile.get_service_years_display}}</li>
                        <li>申请职位： {{ application.position }}</li>
                        <li>投递状态： {{ application.get_status_display|switch_application_status }}</li>
                        <li>
{#                            <form action="/cms/position_delete/{{ position.uuid }}/" method="post">#}
{#                                {% csrf_token %}#}
{#                                <button class="btn btn-danger btn-sm" type="submit">删除</button>#}
{#                            </form>#}
                            <a href="/cms/show_application/{{ application.id }}/" class="btn btn-outline-info btn-sm" role="button" value="查看">查看</a>
{#                            <a href="/cms/invitation_create/" class="btn btn-outline-info btn-sm" role="button" value="邀请">邀请</a>#}
{#                            {% if application.status == 1 %}#}
                            <button  class="show-invitation-modal btn btn-outline-primary btn-sm" data-toggle="modal"
                                     data-target="#new-invitation" data-applicant-uuid='{{ application.user.uuid }}'
                                     data-position-uuid='{{ application.position.uuid }}'
                                     data-applicant-name ='{{ application.user.profile.last_name}} {{application.user.profile.first_name }}'
                                     data-position-name ='{{ application.position }}'
                                     data-application-id ={{ application.id }}>邀请</button>
                            <button class="btn btn-outline-danger btn-sm" type="button" value="回绝"
                            onclick="reject_application('/cms/application_reject/{{ application.id }}/')">回绝</button>
{#                            {% endif %}#}
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <h2>面试邀请管理</h2>
    {% if sent_invitations %}
        <ul>
            {% for invitation in sent_invitations %}
                <li>
                    <ul>
                        <li>应聘者： {{ invitation.user.profile.last_name}} {{invitation.user.profile.first_name }}</li>
                        <li>应聘者学历： {{ invitation.user.profile.get_edu_degree_display}}</li>
                        <li>应聘者工作经验： {{ invitation.user.profile.get_service_years_display}}</li>
                        <li>应聘职位： {{ invitation.position }}</li>
                        <li>面试邀请状态： {{ invitation.get_status_display}}</li>
                        <li>面试时间： {{ invitation.interview_time}}</li>
                        <li>面试地点： {{ invitation.interview_address}}</li>
                        <li>
{#                            <form action="/cms/position_delete/{{ position.uuid }}/" method="post">#}
{#                                {% csrf_token %}#}
{#                                <button class="btn btn-danger btn-sm" type="submit">删除</button>#}
{#                            </form>#}
                            <a href="/cms/show_invitation/{{ invitation.id }}/" class="btn btn-outline-info btn-sm" role="button" value="查看">查看</a>
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>

    {% endif %}

{% endblock %}

{% block javascript %}
    <script>
        function delete_position(edit_url) {
                $.ajax({
                    url: edit_url,
                    {#headers: {"Authorization": token},#}
                    type: 'POST',
                    success: function(result) {
                        // Do something with the result
                        console.log(result)
                    },
                    error: function (error) {
                        console.log(error)
                    }
            });}

        function reject_application(to_url){
            $.ajax({
                    url: to_url,
                    {#headers: {"Authorization": token},#}
                    type: 'POST',
                    success: function(result) {
                        // Do something with the result
                        alert(result);
                    },
                    error: function (error) {
                        console.log(error)
                    }
            });
        }

        $(document).on("click", ".show-invitation-modal", function () {
            var applicant_uuid = $(this).data('applicant-uuid');
            var position_uuid = $(this).data('position-uuid');
            var applicant_name = $(this).data('applicant-name');
            var position_name = $(this).data('position-name');
            var application_id = $(this).data('application-id');
            $(" #id_user_uuid").val( applicant_uuid );
            $(" #id_position_uuid").val( position_uuid );
            $(" #modal-applicant-name").html( applicant_name);
            $(" #modal-position-name").html( position_name );
            $(" #id_application").val( application_id);
        });
    </script>

{% endblock %}

cms/templates/receivedApplications.html
{% extends 'base.html' %}

{% block title %}申请管理{% endblock %}

{% block content %}

    {% load cms_my_filter %}
    <h2>投递管理</h2>
    {% if received_applications %}
        {% if invitation_form %}
            {% include 'modal_base_createInvitation.html' with modal_form_id="new-invitation" modal_form_title="Create a New Invitation" modal_form_method="POST" modal_form_action="/cms/invitation_create/" form=invitation_form %}
        {% endif %}
        <ul>
            {% for application in received_applications %}
                <li>
                    <ul>
                        <li>申请人： {{ application.user.profile.last_name}} {{application.user.profile.first_name }}</li>
                        <li>申请人学历： {{ application.user.profile.get_edu_degree_display}}</li>
                        <li>申请人工作经验： {{ application.user.profile.get_service_years_display}}</li>
                        <li>申请职位： {{ application.position }}</li>
                        <li>投递状态： {{ application.get_status_display|switch_application_status }}</li>
                        <li>
{#                            <form action="/cms/position_delete/{{ position.uuid }}/" method="post">#}
{#                                {% csrf_token %}#}
{#                                <button class="btn btn-danger btn-sm" type="submit">删除</button>#}
{#                            </form>#}
                            <a href="/cms/show_application/{{ application.id }}/" class="btn btn-outline-info btn-sm" role="button" value="查看">查看</a>
{#                            <a href="/cms/invitation_create/" class="btn btn-outline-info btn-sm" role="button" value="邀请">邀请</a>#}
{#                            {% if application.status == 1 %}#}
                            <button  class="show-invitation-modal btn btn-outline-primary btn-sm" data-toggle="modal"
                                     data-target="#new-invitation" data-applicant-uuid='{{ application.user.uuid }}'
                                     data-position-uuid='{{ application.position.uuid }}'
                                     data-applicant-name ='{{ application.user.profile.last_name}} {{application.user.profile.first_name }}'
                                     data-position-name ='{{ application.position }}'
                                     data-application-id ={{ application.id }}>邀请</button>
                            <button class="btn btn-outline-danger btn-sm" type="button" value="回绝"
                            onclick="reject_application('/cms/application_reject/{{ application.id }}/')">回绝</button>
{#                            {% endif %}#}
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

{% block javascript %}
    <script>
        function reject_application(to_url){
            $.ajax({
                    url: to_url,
                    {#headers: {"Authorization": token},#}
                    type: 'POST',
                    success: function(result) {
                        // Do something with the result
                        alert(result);
                    },
                    error: function (error) {
                        console.log(error)
                    }
            });
        }

        $(document).on("click", ".show-invitation-modal", function () {
            var applicant_uuid = $(this).data('applicant-uuid');
            var position_uuid = $(this).data('position-uuid');
            var applicant_name = $(this).data('applicant-name');
            var position_name = $(this).data('position-name');
            var application_id = $(this).data('application-id');
            $(" #id_user_uuid").val( applicant_uuid );
            $(" #id_position_uuid").val( position_uuid );
            $(" #modal-applicant-name").html( applicant_name);
            $(" #modal-position-name").html( position_name );
            $(" #id_application").val( application_id);
        });
    </script>

{% endblock %}

cms/templates/showApplication.html
{% extends 'base.html' %}

{% block title %}详细信息{% endblock %}

{% block javascript %}
    <script>
        $( document ).ready(function() {
        var location =  window.location;
        var new_href = location.protocol + '//' + location.host+'/media/'+ $('#pdf-link').attr("href");
        $('#pdf-link').attr("href", new_href);
        });
    </script>

{% endblock %}


{% block content %}
  <h2>详细信息</h2>
    {% if messages %}
        <div class="span12">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message|safe }}
            </div>
        {% endfor %}
        </div>
    {% endif %}
    {% if application %}
        <ul>
            <li>申请人： {{ application.user.profile.last_name}} {{application.user.profile.first_name }}</li>
            <li>申请职位： {{ application.position}}</li>
        </ul>
        <h3>申请人资料</h3>
        <ul>
            <li>学历： {{ application.user.profile.get_edu_degree_display}}</li>
            <li>工作经验： {{ application.user.profile.get_service_years_display}}</li>
            <li>个人电话： {{ application.user.profile.tel}}</li>
            <li>邮箱： {{ application.user.profile.email}}</li>
            <li>现居地： {{ application.user.profile.address}}</li>
            <li>个人简介： {{ application.user.profile.description}}</li>
        </ul>
        <h3>教育经历</h3>
        {% if edu_exps %}
            {% for edu_exp in edu_exps%}
            <ul>
                <li>学校： {{ edu_exp.college }}</li>
                <li>专业： {{ edu_exp.major }}</li>
                <li>毕业时间： {{ edu_exp.graduate_date }}</li>
                <li>学位： {{ edu_exp.get_degree_display }}</li>
            </ul>
            {% endfor %}
        {% endif %}
        <h3>工作经历</h3>
        {% if work_exps %}
            {% for work_exp in work_exps%}
            <ul>
                <li>任职公司： {{ work_exp.company }}</li>
                <li>任职学位： {{ work_exp.position }}</li>
                <li>开始时间： {{ work_exp.start_date }}</li>
                <li>结束时间： {{ work_exp.end_date }}</li>

            </ul>
            {% endfor %}
        {% endif %}
        <h3>技能</h3>
        {% if skills %}
            {% for skill in skills%}
            <ul>
                <li>技能： {{ skill.name }}</li>
                <li>程度： {{ skill.get_level_display }}</li>
            </ul>
            {% endfor %}
        {% endif %}
        <h3>简历</h3>
        <ul>
            {% if resumes %}
            <ul>
            {% for resume in resumes%}
                <li>
                简历:
                <a href="{{ resume.resume }}" id="pdf-link" class="btn btn-outline-info btn-sm" role="button" value="查看">查看</a>
                </li>
            {% endfor %}
            </ul>

        {% endif %}
        </ul>
    {% endif %}
        <li>
            <a href="/cms/dashboard/" class="btn btn-outline-info btn-sm" role="button" value="返回">返回</a>
        </li>

{% endblock %}